-- MySQL Script generated by MySQL Workbench
-- Sun Apr 17 12:44:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carrito_compras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carrito_compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carrito_compras` DEFAULT CHARACTER SET utf8 ;
USE `carrito_compras` ;

-- -----------------------------------------------------
-- Table `carrito_compras`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrito_compras`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrito_compras`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrito_compras`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_rol_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `carrito_compras`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrito_compras`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrito_compras`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `foto` LONGBLOB NULL,
  `descripcion` VARCHAR(200) NULL,
  `precio` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrito_compras`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrito_compras`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `monto_total` DOUBLE NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `carrito_compras`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrito_compras`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrito_compras`.`detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` DOUBLE NOT NULL,
  `precio` DOUBLE NOT NULL,
  `venta_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_venta_productos1_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_detalle_venta_venta1_idx` (`venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_venta_productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `carrito_compras`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `carrito_compras`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrito_compras`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrito_compras`.`pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha` DATETIME NOT NULL,
  `venta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pago_venta1_idx` (`venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_pago_venta1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `carrito_compras`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
